// Code generated by Kitex v0.3.1. DO NOT EDIT.

package videoservice

import (
	"context"
	"douyin/v1/kitex_gen/video"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return videoServiceServiceInfo
}

var videoServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "VideoService"
	handlerType := (*video.VideoService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetPublishListByUser": kitex.NewMethodInfo(getPublishListByUserHandler, newVideoServiceGetPublishListByUserArgs, newVideoServiceGetPublishListByUserResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "video",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.3.1",
		Extra:           extra,
	}
	return svcInfo
}

func getPublishListByUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceGetPublishListByUserArgs)
	realResult := result.(*video.VideoServiceGetPublishListByUserResult)
	success, err := handler.(video.VideoService).GetPublishListByUser(ctx, realArg.UserId)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceGetPublishListByUserArgs() interface{} {
	return video.NewVideoServiceGetPublishListByUserArgs()
}

func newVideoServiceGetPublishListByUserResult() interface{} {
	return video.NewVideoServiceGetPublishListByUserResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetPublishListByUser(ctx context.Context, userId int64) (r *video.PublishListResponse, err error) {
	var _args video.VideoServiceGetPublishListByUserArgs
	_args.UserId = userId
	var _result video.VideoServiceGetPublishListByUserResult
	if err = p.c.Call(ctx, "GetPublishListByUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
