// Code generated by Kitex v0.3.1. DO NOT EDIT.

package commentactionservice

import (
	"context"
	"douyin/v1/kitex_gen/comment_action"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PostCommentActionResponse(ctx context.Context, req *comment_action.Comment_Action, callOptions ...callopt.Option) (r *comment_action.CommentActionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentActionServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentActionServiceClient struct {
	*kClient
}

func (p *kCommentActionServiceClient) PostCommentActionResponse(ctx context.Context, req *comment_action.Comment_Action, callOptions ...callopt.Option) (r *comment_action.CommentActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PostCommentActionResponse(ctx, req)
}
