// Code generated by Kitex v0.3.1. DO NOT EDIT.
package videocommentsservice

import (
	"douyin/v1/kitex_gen/video_comments"
	"github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler video_comments.VideoCommentsService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
