// Code generated by Kitex v0.3.1. DO NOT EDIT.
package commentactionservice

import (
	"douyin/v1/kitex_gen/comment_action"
	"github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler comment_action.CommentActionService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
